project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex_1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex02/handson2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on/Handson_Ex3/Handson3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on/Handson_Ex4/Handson4.qmd
      - text: In-Class Exercise
        menu:
          - text: In-Class Exercise 1
            href: Inclass-ex1/inclass-ex1.qmd
          - text: In-Class Exercise 2
            href: Inclass/Inclass2/Inclass2.qmd
          - text: In-Class Exercise 3
            href: Inclass/Inclass3/Inclass3.qmd
          - text: In-Class Exercise 4
            href: Inclass/Inclass4/Inclass4.qmd
      - text: Take Home Exercise
        menu:
          - text: Take-Home Exercise 1
            href: Takehome/Takehome1/takehome1.qmd
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

