project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex_1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex02/handson2.qmd
      - text: In-Class Exercise
        menu:
          - text: In-Class Exercise 1
            href: Inclass-ex1/inclass-ex1.qmd
          - text: In-Class Exercise 2
            href: Inclass/Inclass2/Inclass2.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

